# Define a name for workflow
name: CI workflow

# Define an event and branches 
on:
  push:
    branches: ['main']
  pull_request:
    branches:
      - "main"

# Define jobs
jobs:
  build:
    # Define a runner for job
    runs-on: ubuntu-latest
    # Lets run container on runner
    container: python:3.9-slim
    # Define steps
    steps:
      - name: Checkout
        # This one uses action
        uses: actions/checkout@v3
      - name: Show working folder
        run: pwd
      - name: List files in workdir
        run: ls -ltra
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt    
